from code_golf import twelve_days_of_christmas


# In the file `twelve_days_of_christmas.py`, create a variable named `song` that is the entire text of the song
#   "The Twelve Days of Christmas" using as little code as possible.

# This unit test checks that the resulting text is correct according to this version of the lyrics


def test_twelve_days_of_christmas():
    assert twelve_days_of_christmas.song == (
        "On the first day of Christmas my true love gave to me\n"
        "a partridge in a pear tree.\n"
        "\n"
        "On the second day of Christmas my true love gave to me\n"
        "two turtle-doves\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the third day of Christmas my true love gave to me\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the fourth day of Christmas my true love gave to me\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the fifth day of Christmas my true love gave to me\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the sixth day of Christmas my true love gave to me\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the seventh day of Christmas my true love gave to me\n"
        "seven swans a-swimming,\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the eighth day of Christmas my true love gave to me\n"
        "eight maids a-milking,\n"
        "seven swans a-swimming,\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the ninth day of Christmas my true love gave to me\n"
        "nine drummers drumming,\n"
        "eight maids a-milking,\n"
        "seven swans a-swimming,\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the tenth day of Christmas my true love gave to me\n"
        "ten pipers piping,\n"
        "nine drummers drumming,\n"
        "eight maids a-milking,\n"
        "seven swans a-swimming,\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the eleventh day of Christmas my true love gave to me\n"
        "eleven ladies dancing,\n"
        "ten pipers piping,\n"
        "nine drummers drumming,\n"
        "eight maids a-milking,\n"
        "seven swans a-swimming,\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree.\n"
        "\n"
        "On the twelfth day of Christmas my true love gave to me\n"
        "twelve lords a-leaping,\n"
        "eleven ladies dancing,\n"
        "ten pipers piping,\n"
        "nine drummers drumming,\n"
        "eight maids a-milking,\n"
        "seven swans a-swimming,\n"
        "six geese a-laying,\n"
        "five gold rings,\n"
        "four calling birds,\n"
        "three French hens,\n"
        "two turtle-doves,\n"
        "and a partridge in a pear tree."
        )
